// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Models;

#nullable disable

namespace TechStoreWeb.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606161905_CartIntegrated")]
    partial class CartIntegrated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore.Models.AdminUsers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AdminUserss");
                });

            modelBuilder.Entity("TechStore.Models.CartItem", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ImagePro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("TechStore.Models.Category", b =>
                {
                    b.Property<string>("IDCate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameCate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCate");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("TechStore.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDCus")
                        .HasColumnType("int");

                    b.Property<bool>("IsFromSupport")
                        .HasColumnType("bit");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("AdminID");

                    b.HasIndex("IDCus");

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("TechStore.Models.Customer", b =>
                {
                    b.Property<int>("IDCus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCus"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is2FAEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAnalyticEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVIP")
                        .HasColumnType("bit");

                    b.Property<string>("MembershipLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassCus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneCus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonBanned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("TwoFactorSecret")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCus");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TechStore.Models.LoveProducts", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductsProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductsProductID");

                    b.ToTable("LoveProducts");
                });

            modelBuilder.Entity("TechStore.Models.OrderDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IDOrder")
                        .HasColumnType("int");

                    b.Property<int>("IDProduct")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("IDOrder");

                    b.HasIndex("IDProduct");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("TechStore.Models.OrderPro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AddressDeliverry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOrder")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDCus")
                        .HasColumnType("int")
                        .HasColumnName("IDCus");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDCus");

                    b.ToTable("OrderPro");
                });

            modelBuilder.Entity("TechStore.Models.Products", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecriptionPro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImagePro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("Category");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TechStore.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReviewContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TechStore.Models.ShippingProvider", b =>
                {
                    b.Property<string>("ProviderCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiCancelOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiCheckStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiCreateOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("PriceExpress")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceFast")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceStandard")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SupportExpress")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportFast")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportStandard")
                        .HasColumnType("bit");

                    b.HasKey("ProviderCode");

                    b.ToTable("ShippingProvider");
                });

            modelBuilder.Entity("TechStore.Models.CartItem", b =>
                {
                    b.HasOne("TechStore.Models.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechStore.Models.ChatMessage", b =>
                {
                    b.HasOne("TechStore.Models.AdminUsers", "AdminUsers")
                        .WithMany()
                        .HasForeignKey("AdminID");

                    b.HasOne("TechStore.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("IDCus");

                    b.Navigation("AdminUsers");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TechStore.Models.LoveProducts", b =>
                {
                    b.HasOne("TechStore.Models.Customer", "Customer")
                        .WithMany("LoveProducts")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Models.Products", "Products")
                        .WithMany("LoveProducts")
                        .HasForeignKey("ProductsProductID");

                    b.Navigation("Customer");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechStore.Models.OrderDetails", b =>
                {
                    b.HasOne("TechStore.Models.OrderPro", "OrderPro")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IDOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Models.Products", "Products")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IDProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderPro");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechStore.Models.OrderPro", b =>
                {
                    b.HasOne("TechStore.Models.Customer", "Customer")
                        .WithMany("OrderPro")
                        .HasForeignKey("IDCus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TechStore.Models.Products", b =>
                {
                    b.HasOne("TechStore.Models.Category", "Category1")
                        .WithMany("Products")
                        .HasForeignKey("Category");

                    b.Navigation("Category1");
                });

            modelBuilder.Entity("TechStore.Models.Review", b =>
                {
                    b.HasOne("TechStore.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Models.Products", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechStore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechStore.Models.Customer", b =>
                {
                    b.Navigation("LoveProducts");

                    b.Navigation("OrderPro");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TechStore.Models.OrderPro", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("TechStore.Models.Products", b =>
                {
                    b.Navigation("LoveProducts");

                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
