//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Models
{
    using System;
    using Microsoft.EntityFrameworkCore;
    
    public partial class DBTechStoreEntities : DbContext
    {
        public DBTechStoreEntities(DbContextOptions<DBTechStoreEntities> options) 
    : base(options)
    {
    }
    
        
    
        public virtual DbSet<AdminUsers> AdminUsers { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<LoveProducts> LoveProducts { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<OrderPro> OrderPro { get; set; }
        public virtual DbSet<ShippingProvider> ShippingProvider { get; set; }

        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<OTPModel> OTPModels { get; set; }
 
        public virtual DbSet<SupportRequest> SupportRequests { get; set; }
    }
}
