//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class OrderDetails
    {
        [Key]
        public int ID { get; set; }
        public int IDProduct { get; set; }
       
        public int IDOrder { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public Nullable<double> Subtotal { get; set; }
        public string Note { get; set; }
    
        [ForeignKey("IDOrder")]
        public virtual OrderPro OrderPro { get; set; }
        [ForeignKey("IDProduct")] //Khóa ngoại là cột gì trong bảng này nối tới cột của bảng kia 
        public virtual Products Products { get; set; }
    }
}
