//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class OrderPro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPro()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
        [Key]
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        [Column("IDCus")]
        public int IDCus { get; set; }
        public string AddressDeliverry { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string TrackingNumber { get; set; }
        public string ShippingCode {get;set;}
        public string PaymentStatus { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        [ForeignKey("IDCus")] //fix bug lỗi sai tên cột nếu có bảng sql này là 2 trong 1 
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
