//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.LoveProducts = new HashSet<LoveProducts>();
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Reviews = new HashSet<Review>();
        }
        [Key]
        [DisplayName("ID sản phẩm")]
        public int ProductID { get; set; }
        [DisplayName("Tên sản phẩm")]
        public string NamePro { get; set; }
        [DisplayName("Mô tả sản phẩm")]
        public string DecriptionPro { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
        public string ImagePro { get; set; }
        public Nullable <decimal>Discount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }

        [ForeignKey("Category")]
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoveProducts> LoveProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
