//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        [Key]
        public int ReviewID { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public decimal Rating { get; set; }
        public string ReviewContent { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ReviewerName { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public Nullable<bool> IsBanned { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Products Product { get; set; }
    }
}
