//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ShippingProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShippingProvider()
        {
            
        }
        [Key]
        public string ProviderCode { get; set; }
        public string ProviderName { get; set; }
        public string ApiToken { get; set; }
        public bool IsActive { get; set; }
        public string ApiCreateOrder { get; set; }
        public string ApiCancelOrder { get; set; }
        public string ApiCheckStatus { get; set; }
        public bool SupportFast { get; set; }      //GH Nhanh
        public bool SupportStandard { get; set; } 
        public bool SupportExpress { get; set; } // Hoa toc
        public decimal PriceFast{get ;set;}
        public decimal PriceStandard{get ;set;}
        public decimal PriceExpress{get ;set;}


    
    
    }
}
